# Generated by Django 4.1.7 on 2023-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_variation_productimage_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cake_category',
            field=models.CharField(choices=[], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavour_category',
            field=models.CharField(choices=[], max_length=120),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[], max_length=120),
        ),
    ]
